name: Deploy Infrastructure and Bot

on:
  push:
    branches:
      - main # Change this to your branch name

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  LOCATION: ${{ secrets.AZURE_LOCATION }} # Assuming you also store the location as a secret

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID

      - name: Deploy Bicep template
        run: az deployment group create --resource-group YOUR_RESOURCE_GROUP_NAME --template-file path/to/your-bicep-file.bicep --parameters location=$LOCATION

      - name: Log out of Azure
        run: az logout

  deploy_bot:
    needs: deploy_infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID

      - name: Deploy to Function App
        uses: azure/functions-action@v1
        with:
          app-name: GitDerektTradesFunctionApp
          package: path/to/bot-code

      - name: Log out of Azure
        run: az logout
