name: Deploy Default

on:
  push:
    branches:
      - main

jobs:
  trigger_app_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Bot Deployment
        run: |
          curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/DerekCL/GitDerekt-Trades/dispatches \
               -d '{"event_type": "deploy-bot"}'
