name: Deploy Infrastructure

on:
  workflow_dispatch: # This allows manual triggering of the workflow

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
  AZURE_DEPLOYMENT_LOCATION: ${{ env.AZURE_DEPLOYMENT_LOCATION }}

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: az login --service-principal -u ${{ env.CLIENT_ID }} -p ${{ env.CLIENT_SECRET }} --tenant ${{ env.TENANT_ID }}

      - name: Deploy Bicep template
        run: az deployment group create --resource-group ${{ env.RESOURCE_GROUP_NAME }} --template-file main.bicep --parameters location=${{ env.AZURE_DEPLOYMENT_LOCATION }}

      - name: Log out of Azure
        run: az logout
